name: Conditional Generate JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read theme.yml
        id: read-theme
        run: |
          # Install yq for parsing YAML files
          wget https://github.com/mikefarah/yq/releases/download/v4.30.8/yq_linux_amd64 -O ./yq
          chmod +x ./yq
          # Extract the value of the key from _data/theme.yml
          VALUE=$(./yq '.json-generation' _data/theme.yml)
          echo "json_generation=$VALUE" >> $GITHUB_ENV

      - name: Run Rake Task if Condition is True
        if: env.json_generation == 'true'
        run: |
          bundle install
          rake generate_json
