name: Conditional Generate JSON

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read theme.yml
        id: read-theme
        run: |
          # Install yq for parsing YAML files
          sudo apt-get update && sudo apt-get install -y yq
          # Extract the value of the key (e.g., "generate_json") from _data/theme.yml
          VALUE=$(yq eval '.json-generation' _data/theme.yml)
          echo "json-generation=$VALUE" >> $GITHUB_ENV

      - name: Run Rake Task if Condition is True
        if: env.json-generation == 'true'
        run: |
          bundle install
          rake generate_json
